name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: ${{ matrix.task }} / ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: [fmt, lint, test]
        go-version: ["1.25.1"]

    steps:
      - uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-project
        with:
          go-version: ${{ matrix.go-version }}
          golanci-lint-version: "v2.3.1"
          just-version: "1.45.0"

      - name: Check formatting
        if: matrix.task == 'fmt'
        run: |
          just fmt-check
          git diff --exit-code

      - name: Lint
        if: matrix.task == 'lint'
        run: just lint

      - name: Test with Coverage
        if: matrix.task == 'test'
        run: just unit-test-coverage

      - name: Coverage Report
        if: matrix.task == 'test'
        uses: k1LoW/octocov-action@v1
